imap     jk        <Esc>
nnoremap tl        :tabnext<CR>
nnoremap th        :tabprev<CR>
nnoremap tt        :tabedit<Space>
nnoremap tn        :tabnew<Space>
nnoremap tm        :tabm<Space>
nnoremap td        :tabclose<CR>
nnoremap <space>   zz
map      <leader>c :nohlsearch<cr>
